export enum EmojiCommitTypes {
   BREAKING_CHANGE = '🚨 BREAKING CHANGE',
   FIX = '🩹 fix',
   CI = '🤖 ci',
   BUILD = '🛠️ build',
   CHORE = '🧹 chore',
   DOCS = '📚 docs',
   FEAT = '✨ feat',
   PERF = '⚡️ perf',
   REFACTOR = '♻️ refactor',
   REVERT = '⏪ revert',
   STYLE = '🎨 style',
   TEST = '🧪 test',
   ANIMATIONS = '🎭 animations',
   COMMON = '🌍 common',
   COMPILER = '🔍 compiler',
   COMPILER_CLI = '🔧 compiler-cli',
   CORE = '💙 core',
   ELEMENTS = '🧩 elements',
   FORMS = '📝 forms',
   HTTP = '📡 http',
   LANGUAGE_SERVICE = '🗣️ language-service',
   PLATFORM_BROWSER = '🌐 platform-browser',
   PLATFORM_BROWSER_DYNAMIC = '🌌 platform-browser-dynamic',
   PLATFORM_SERVER = '🖥️ platform-server',
   PLATFORM_WEBWORKER = '🕸️ platform-webworker',
   PLATFORM_WEBWORKER_DYNAMIC = '🕷️ platform-webworker-dynamic',
   ROUTER = '🛣️ router',
   SERVICE_WORKER = '📊 service-worker',
   UPGRADE = '⬆️ upgrade',
   PACKAGING = '📦 packaging',
   CHANGELOG = '📜 changelog',
   AIO = '📘 aio',
}

export function isBreakingChange(commitType: string): boolean {
   return commitType.includes(EmojiCommitTypes.BREAKING_CHANGE) || commitType.endsWith('❗')
}
